'use client'

import { useEffect, useMemo, useState } from 'react'
import { Check, ChevronDown, ChevronLeft, ChevronRight, Clipboard, Clock3, Heart, Menu, Pause, Play, RotateCcw, Sparkles, X } from 'lucide-react'

const prompts = [
  { id: 1, title: 'Explain a difficult topic', role: 'Student', topic: 'Study', text: 'Act as a patient tutor. Explain [topic] for a beginner using one analogy, three key terms, and a short quiz. Flag anything I should verify.' },
  { id: 2, title: 'Make a study plan', role: 'Student', topic: 'Study', text: 'Create a realistic study plan for [subject] over [time]. Include focused blocks, active recall, breaks, and one way to check my progress.' },
  { id: 3, title: 'Give feedback on a draft', role: 'Student', topic: 'Create', text: 'Review this draft for clarity and structure. Name two strengths, three specific improvements, and one question a reader may still have.' },
  { id: 4, title: 'Plan a class discussion', role: 'Teacher', topic: 'Teaching', text: 'Design a 20-minute discussion about [topic] for [level]. Include an opening question, three follow-ups, and an inclusive exit ticket.' },
  { id: 5, title: 'Differentiate an activity', role: 'Teacher', topic: 'Teaching', text: 'Adapt this activity for learners who need more scaffolding and learners ready for a challenge. Keep the learning goal the same.' },
  { id: 6, title: 'Create an invitation', role: 'Student', topic: 'Everyday', text: 'Write a warm invitation for [event] to [audience]. Keep it under 100 words and include the essential details as a clear list.' },
  { id: 7, title: 'Summarize a paper carefully', role: 'Researcher', topic: 'Research', text: 'Summarize this paper by separating the research question, method, findings, limitations, and claims that require checking. Do not infer beyond the text.' },
  { id: 8, title: 'Compare two sources', role: 'Researcher', topic: 'Research', text: 'Compare these sources on their evidence, assumptions, date, and limitations. Quote only when useful and identify where they disagree.' },
  { id: 9, title: 'Turn notes into questions', role: 'Student', topic: 'Study', text: 'Turn these notes into 10 retrieval-practice questions. Mix definitions, applications, and one question that connects two ideas.' },
  { id: 10, title: 'Brainstorm campaign ideas', role: 'Teacher', topic: 'Create', text: 'Generate five campaign concepts for [brief]. For each, name the audience, message, medium, and one risk to consider.' },
  { id: 11, title: 'Find what to verify', role: 'Researcher', topic: 'Everyday', text: 'Read this answer and mark each factual claim. For every claim, suggest the kind of original source I should consult.' },
]

const examples = [
  { name: 'Study', vague: 'Explain photosynthesis.', improved: 'Explain photosynthesis to a 13-year-old using a simple plant analogy, three key terms, and a 3-question quiz. Separate facts I should verify.' },
  { name: 'Invitation', vague: 'Write an invite for our event.', improved: 'Write a friendly 80-word invitation for a campus repair cafe on Friday at 4pm in the library. Include who it is for, what to bring, and a clear call to action.' },
  { name: 'Weekly plan', vague: 'Plan my week.', improved: 'Help me plan Monday–Friday around classes 9–2, two 45-minute study blocks, exercise, meals, and one evening off. Ask one question before making assumptions.' },
]

function CopyButton({ text, label = 'Copy' }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false)
  return <button className="icon-button" onClick={async () => { try { await navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1400) } catch {} }} aria-label={`${label} text`}><Clipboard size={15} /> {copied ? 'Copied' : label}</button>
}

function SectionHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) {
  return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{children}</div>
}

export default function AIStarter() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [tasks, setTasks] = useState([false, false, false])
  const [goal, setGoal] = useState('Understand a topic')
  const [audience, setAudience] = useState('a curious beginner')
  const [format, setFormat] = useState('a clear explanation with examples')
  const [example, setExample] = useState(0)
  const [role, setRole] = useState('All roles')
  const [topic, setTopic] = useState('All')
  const [search, setSearch] = useState('')
  const [favorites, setFavorites] = useState<number[]>([])
  const [showFavorites, setShowFavorites] = useState(false)
  const [walkthrough, setWalkthrough] = useState(0)
  const [playing, setPlaying] = useState(false)
  const [answer, setAnswer] = useState<string | null>(null)
  const [details, setDetails] = useState<string[]>([])
  const [seconds, setSeconds] = useState(900)
  const [timerRunning, setTimerRunning] = useState(false)
  const [feedback, setFeedback] = useState('')

  useEffect(() => { try { const saved = window.localStorage.getItem('ai-starter-favorites'); if (saved) setFavorites(JSON.parse(saved)) } catch {} }, [])
  useEffect(() => { try { window.localStorage.setItem('ai-starter-favorites', JSON.stringify(favorites)) } catch {} }, [favorites])
  useEffect(() => { if (!playing) return; const id = window.setInterval(() => setWalkthrough((step) => (step + 1) % 3), 15000); return () => window.clearInterval(id) }, [playing])
  useEffect(() => { if (!timerRunning || seconds <= 0) return; const id = window.setInterval(() => setSeconds((value) => value - 1), 1000); return () => window.clearInterval(id) }, [timerRunning, seconds])

  const generated = `Act as a helpful guide for ${audience}. Help me ${goal}. Respond with ${format}. State assumptions, distinguish suggestions from facts, and end with one way I can verify the result.`
  const filtered = useMemo(() => prompts.filter((item) => (!showFavorites || favorites.includes(item.id)) && (role === 'All roles' || item.role === role) && (topic === 'All' || item.topic === topic) && `${item.title} ${item.text}`.toLowerCase().includes(search.toLowerCase())), [role, topic, search, favorites, showFavorites])
  const toggleDetail = (name: string) => setDetails((items) => items.includes(name) ? items.filter((item) => item !== name) : [...items, name])
  const minutes = String(Math.floor(seconds / 60)).padStart(2, '0'); const secs = String(seconds % 60).padStart(2, '0')

  return <div className="site-shell">
    <div className="progress" aria-hidden="true" />
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><a className="brand" href="#top"><span className="brand-mark"><Sparkles size={16} /></span> AI Starter</a><button className="mobile-menu" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle navigation">{mobileOpen ? <X /> : <Menu />}</button><nav className={mobileOpen ? 'nav open' : 'nav'}>{['Start here','Prompts','Teachers','Responsible use','Tools','FAQ','Feedback'].map((item) => <a key={item} href={`#${item.toLowerCase().replaceAll(' ', '-')}`} onClick={() => setMobileOpen(false)}>{item}</a>)}</nav></header>
    <main id="main">
      <section className="hero wrap" id="top"><div className="hero-copy"><span className="eyebrow">A friendly field guide to AI</span><h1>Small prompts.<br /><em>Big possibilities.</em></h1><p className="hero-lede">You don&apos;t need to be a tech expert to use AI. Learn the basics, build a better prompt, and turn your first idea into something useful.</p><div className="hero-actions"><a className="button primary" href="#start-here">Start the five-minute path <ChevronRight size={16} /></a><a className="button ghost" href="#walkthrough">See the walkthrough</a></div><div className="hero-note"><span className="signal-dot" /> Built for students, teachers, and researchers <span className="divider" /> No account. No hype.</div></div><div className="hero-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="prompt-card float-one"><span className="card-label">YOUR FIRST PROMPT</span><p>“Explain this like I&apos;m curious, not clueless.”</p><div className="mini-line" /><span className="muted">Clear goal · Right context</span></div><div className="stat-card float-two"><span className="stat-number">05</span><span className="muted">minutes to<br />get started</span></div><div className="quote-card float-three"><span className="quote-mark">“</span><p>Good AI use is less about getting answers and more about asking better questions.</p></div></div></section>
      <section className="starting-strip wrap"><p>Choose your starting point</p><div className="starting-grid"><a href="#start-here"><span>01</span><strong>Learn the basics</strong><small>Build a useful mental model</small></a><a href="#prompt-library"><span>02</span><strong>Find a useful prompt</strong><small>Start with something practical</small></a><a href="#critical-thinking"><span>03</span><strong>Test your judgment</strong><small>Practice checking an answer</small></a></div></section>

      <section className="section wrap" id="start-here"><SectionHeading eyebrow="01 / START HERE" title="Start here in 5 minutes"><p>Three tiny tasks. One better relationship with AI.</p></SectionHeading><div className="task-panel"><div className="task-list">{['Ask AI to explain a topic.','Improve the prompt with context and format.','Verify one factual claim using an original source.'].map((task, i) => <label className={tasks[i] ? 'task checked' : 'task'} key={task}><input type="checkbox" checked={tasks[i]} onChange={() => setTasks((items) => items.map((value, index) => index === i ? !value : value))} /><span className="check"><Check size={14} /></span><span><b>{task}</b><small>{i === 0 ? 'Pick something you already want to understand.' : i === 1 ? 'Tell it who you are, what you need, and how to respond.' : 'Look for the source behind the claim, not just another summary.'}</small></span></label>)}</div><div className="completion"><span className="completion-ring">{tasks.filter(Boolean).length}<small>/3</small></span><strong>{tasks.every(Boolean) ? 'You did it.' : 'Keep going.'}</strong><p>{tasks.every(Boolean) ? 'You practiced the core loop: ask, shape, verify.' : 'AI literacy is a practice, not a personality trait.'}</p></div></div></section>

      <section className="section tinted" id="prompts"><div className="wrap"><SectionHeading eyebrow="02 / PROMPT BUILDER" title="Make your first prompt less vague"><p>Give your idea a little more shape. This creates a template, not a live AI response.</p></SectionHeading><div className="builder"><div className="builder-fields"><label>My goal<input value={goal} onChange={(e) => setGoal(e.target.value)} /></label><label>Who is it for?<input value={audience} onChange={(e) => setAudience(e.target.value)} /></label><label>I want the output to be<select value={format} onChange={(e) => setFormat(e.target.value)}><option>a clear explanation with examples</option><option>a short checklist</option><option>a table with pros and cons</option><option>three ideas with next steps</option></select></label></div><div className="generated"><div className="generated-head"><span className="card-label">YOUR TEMPLATE</span><CopyButton text={generated} /></div><p>{generated}</p><span className="template-note">Tip: add constraints, context, and a way to check the answer.</span></div></div></div></section>

      <section className="section wrap"><SectionHeading eyebrow="03 / BEFORE & AFTER" title="A little context goes a long way"><p>Choose an example to see what changes when a prompt gets specific.</p></SectionHeading><div className="example-tabs">{examples.map((item, i) => <button className={example === i ? 'active' : ''} onClick={() => setExample(i)} key={item.name}>{item.name}</button>)}</div><div className="before-after"><div><span className="label coral">VAGUE</span><p>{examples[example].vague}</p></div><div className="arrow"><ChevronRight /></div><div className="improved"><span className="label teal">IMPROVED</span><p>{examples[example].improved}</p><CopyButton text={examples[example].improved} label="Copy prompt" /></div><aside><strong>Why it&apos;s clearer</strong><p>It names the audience, gives useful constraints, and asks for a format that makes the result easier to evaluate.</p></aside></div></section>

      <section className="section tinted" id="prompt-library"><div className="wrap"><SectionHeading eyebrow="04 / PROMPT LIBRARY" title="Borrow a useful starting point"><p>Eleven prompts for real work. Edit them until they sound like you.</p></SectionHeading><div className="filters"><input className="search" placeholder="Search prompts..." value={search} onChange={(e) => setSearch(e.target.value)} aria-label="Search prompts" /><div className="filter-group">{['All roles','Student','Teacher','Researcher'].map((item) => <button className={role === item ? 'active' : ''} onClick={() => setRole(item)} key={item}>{item}</button>)}</div><div className="filter-group">{['All','Study','Create','Everyday','Teaching','Research'].map((item) => <button className={topic === item ? 'active' : ''} onClick={() => setTopic(item)} key={item}>{item}</button>)}</div><button className={showFavorites ? 'favorite-toggle active' : 'favorite-toggle'} onClick={() => setShowFavorites(!showFavorites)}><Heart size={15} fill={showFavorites ? 'currentColor' : 'none'} /> Favorites {favorites.length > 0 && `(${favorites.length})`}</button></div><div className="prompt-grid">{filtered.map((item) => <article className="library-card" key={item.id}><div className="library-meta"><span>{item.role}</span><button className="heart" onClick={() => setFavorites((items) => items.includes(item.id) ? items.filter((id) => id !== item.id) : [...items, item.id])} aria-label="Save favorite"><Heart size={16} fill={favorites.includes(item.id) ? 'currentColor' : 'none'} /></button></div><h3>{item.title}</h3><p>{item.text}</p><div className="library-footer"><span className="topic-pill">{item.topic}</span><CopyButton text={item.text} /></div></article>)}</div>{filtered.length === 0 && <div className="empty">No prompts match that combination. Try clearing a filter or searching a broader term.</div>}</div></section>

      <section className="section wrap"><SectionHeading eyebrow="05 / LEARNING PATHS" title="Pick a path, then make it yours" /><div className="path-grid">{[['Beginner','Start with the core loop: ask, shape, verify.','Study buddy'],['Intermediate','Use AI as a collaborator while keeping your reasoning visible.','Verified paper summary'],['Builder','Design a small system with sources, boundaries, and a human check.','Source-based FAQ chatbot']].map(([name, copy, project], i) => <button className={details.includes(name) ? 'path-card open' : 'path-card'} onClick={() => toggleDetail(name)} key={name}><div className="path-top"><span>0{i + 1}</span><ChevronDown size={18} /></div><h3>{name}</h3><p>{copy}</p>{details.includes(name) && <div className="path-detail"><span>Try this project</span><strong>{project}</strong></div>}</button>)}</div></section>

      <section className="section dark-section" id="walkthrough"><div className="wrap"><SectionHeading eyebrow="06 / QUICK WALKTHROUGH" title="The three-part AI habit"><p>Build a request. Copy it into your tool. Verify what comes back.</p></SectionHeading><div className="walkthrough"><div className="walk-visual"><div className="walk-number">0{walkthrough + 1}</div><div className="walk-orb"><span>{['Build','Copy','Verify'][walkthrough]}</span></div><div className="walk-controls"><button onClick={() => setWalkthrough((walkthrough + 2) % 3)} aria-label="Previous step"><ChevronLeft /></button><button className="play" onClick={() => setPlaying(!playing)} aria-label={playing ? 'Pause playback' : 'Play walkthrough'}>{playing ? <Pause /> : <Play />}</button><button onClick={() => setWalkthrough((walkthrough + 1) % 3)} aria-label="Next step"><ChevronRight /></button></div><span className="play-note">{playing ? 'Playing · 15 seconds per step' : 'Play the 45-second guide'}</span></div><div className="walk-copy">{['Build a request with a clear goal, audience, format, and a way to check the result.','Copy your prompt into an AI tool. Read the response as a draft, not a verdict.','Verify important claims with original sources, your own calculations, or a trusted expert.'].map((text, i) => <button className={walkthrough === i ? 'walk-step active' : 'walk-step'} onClick={() => setWalkthrough(i)} key={text}><span>0{i + 1}</span><p><strong>{['Build','Copy','Verify'][i]}</strong>{text}</p></button>)}</div></div></div></section>

      <section className="section wrap" id="responsible-use"><SectionHeading eyebrow="07 / RESPONSIBLE USE" title="Capability needs a conscience"><p>Use AI to support your thinking, not quietly replace it.</p></SectionHeading><div className="responsibility-grid"><div><div className="notice"><strong>Before you submit</strong><p>Check your assignment policy. Verify sources and calculations. Disclose permitted AI use. Disclosure does not make prohibited use acceptable.</p></div><details><summary>Privacy do&apos;s and don&apos;ts</summary><p>Do remove personal, sensitive, or confidential information. Don&apos;t assume a chat is private or that deleting it erases every copy.</p></details><details><summary>When not to use AI</summary><p>Pause when a decision affects someone&apos;s safety, rights, health, or privacy, or when the task is meant to assess your unaided work.</p></details><details><summary>Bias, copyright, deepfakes, and resource use</summary><p>Outputs can reproduce bias, imitate protected work, or make convincing fakes. Consider whose data and labor shaped the result, and use tools thoughtfully.</p></details></div><div className="disclosure"><span className="card-label">COPYABLE DISCLOSURE</span><p>“I used [tool and model/version, if known] on [date] to [purpose]. I revised [changes] and verified [claims] using [sources or method].”</p><CopyButton text="I used [tool and model/version, if known] on [date] to [purpose]. I revised [changes] and verified [claims] using [sources or method]." label="Copy disclosure" /></div></div></section>

      <section className="section tinted" id="critical-thinking"><div className="wrap"><SectionHeading eyebrow="08 / CRITICAL THINKING" title="Can you catch the confident mistake?"><p>AI-generated does not mean automatically checked. What should you do with this answer?</p></SectionHeading><div className="exercise"><div className="ai-answer"><span className="card-label">FICTIONAL AI ANSWER</span><p>“Study sessions of 20, 30, and 40 minutes total 100 minutes, or 1 hour and 40 minutes.”</p></div><div className="choices"><p><strong>Your move:</strong></p>{['Trust it because it sounds confident.','Ask it to repeat the same calculation.','Calculate it yourself and verify the result.'].map((choice, i) => <button className={answer === choice ? 'selected' : ''} onClick={() => setAnswer(choice)} key={choice}>{String.fromCharCode(65 + i)} <span>{choice}</span></button>)}{answer && <div className={answer.startsWith('Calculate') ? 'feedback good' : 'feedback'}><strong>{answer.startsWith('Calculate') ? 'Exactly.' : 'Not quite.'}</strong> The correct total is 90 minutes, or 1 hour and 30 minutes. Confidence and repeated agreement are not verification.</div>}</div></div></div></section>

      <section className="section wrap" id="tools"><SectionHeading eyebrow="09 / TOOLS" title="A quick comparison, not a winner" /><div className="tools-table"><div className="table-row table-head"><span>Tool</span><span>Free option</span><span>Paid option</span><span>Useful starting tasks</span></div>{[['ChatGPT','Check official page','Check official page','Brainstorming, explanations'],['Claude','Check official page','Check official page','Long-form writing, analysis'],['Microsoft Copilot','Check official page','Check official page','Everyday questions, drafting']].map((row) => <div className="table-row" key={row[0]}>{row.map((cell, i) => <span key={cell}>{i === 0 ? <strong>{cell}</strong> : cell}</span>)}</div>)}</div><p className="table-note">Last reviewed September 2026. Features and pricing change; always check <a href="https://chatgpt.com/pricing" target="_blank" rel="noreferrer">official pricing pages</a> before deciding.</p></section>

      <section className="section tinted" id="teachers"><div className="wrap"><SectionHeading eyebrow="10 / TEACHER TOOLKIT" title="Make the process visible"><p>Simple structures that reward thinking, not just polished output.</p></SectionHeading><div className="toolkit-grid">{[['30-minute AI literacy lesson','A 5-minute prompt demo, 10 minutes comparing vague and specific requests, 10 minutes verifying a claim, and 5 minutes reflecting.'],['Assignment ideas','Ask for process notes, an in-class draft, and a short oral explanation. Grade the reasoning and revision, not just the final prose.'],['A simple rubric','Look for verification, reasoning, revision, and disclosure. For learners without AI access, offer a partner, a library source, or a paper-based equivalent.']].map(([title, text]) => <details className="toolkit-card" key={title}><summary>{title}<ChevronDown size={18} /></summary><p>{text}</p></details>)}</div></div></section>

      <section className="section wrap"><SectionHeading eyebrow="11 / GLOSSARY" title="Words worth knowing" /><div className="glossary">{[['LLM','A language model trained to predict likely sequences of text.'],['Prompt','The instruction or context you give an AI system.'],['Token','A small chunk of text a model processes; it may be a word, part of a word, or punctuation.'],['Hallucination','A confident-sounding output that is unsupported or incorrect.'],['Agent','A system that can plan and take steps toward a goal using tools.'],['RAG','Retrieval-augmented generation: giving a model relevant sources to use while responding.']].map(([term, definition]) => <div key={term}><strong>{term}</strong><p>{definition}</p></div>)}</div></section>

      <section className="section tinted" id="faq"><div className="wrap"><SectionHeading eyebrow="12 / FAQ" title="Questions beginners actually ask" /><div className="faq-grid">{[['Is using AI cheating?','It depends on the task and its rules. Follow the policy, keep your process visible, and ask when the boundary is unclear.'],['Can AI be accurate?','Sometimes. Accuracy varies by topic and tool. Verify important claims rather than relying on confidence or fluency.'],['What about privacy?','Treat prompts as information you are sharing with a service. Remove sensitive details and check the tool’s current privacy controls.'],['Does AI remember me?','Memory features vary. Read the tool’s settings and policy; do not assume a chat is either fully temporary or fully private.'],['What are transformers?','A common neural-network architecture that uses attention to process relationships between parts of an input.'],['Will AI take jobs?','It may change tasks and workflows, but outcomes depend on choices by people, organizations, and policymakers. Avoid universal predictions.'],['How do I improve a disappointing answer?','Name what missed, add context and constraints, ask for a different format, and verify the new result.']].map(([question, response]) => <details key={question}><summary>{question}<ChevronDown size={16} /></summary><p>{response}</p></details>)}</div></div></section>

      <section className="section wrap" id="challenge"><SectionHeading eyebrow="13 / CREATIVE CHALLENGE" title="A 15-minute campus campaign"><p>Practice the full loop with something playful and concrete.</p></SectionHeading><div className="challenge-panel"><div className="challenge-steps"><div><span>01</span><strong>Choose a brief</strong><p>Invite people to a campus event.</p></div><div><span>02</span><strong>Create</strong><p>Make an invitation and poster concept.</p></div><div><span>03</span><strong>Verify & share</strong><p>Check details, improve, and share.</p></div></div><div className="timer"><Clock3 size={18} /><strong>{minutes}:{secs}</strong><span>minutes left</span><div className="timer-actions"><button onClick={() => setTimerRunning(!timerRunning)}>{timerRunning ? <Pause size={15} /> : <Play size={15} />}{timerRunning ? 'Pause' : 'Start'}</button><button onClick={() => { setSeconds(900); setTimerRunning(false) }}><RotateCcw size={15} /> Reset</button></div></div></div></section>

      <section className="section footer-section" id="feedback"><div className="wrap footer-grid"><div><span className="eyebrow">14 / ABOUT & FEEDBACK</span><h2>AI Starter is a small, AI-assisted learning project.</h2><p>Created by Tanusree for people who want a practical, thoughtful place to begin. Updated September 2026.</p><p className="muted">No backend. Feedback is copied, not submitted.</p></div><div className="feedback-box"><label htmlFor="feedback">What would help a beginner?</label><textarea id="feedback" value={feedback} onChange={(e) => setFeedback(e.target.value)} placeholder="Share a thought..." /><div className="feedback-actions"><button className="button ghost" onClick={() => setFeedback('Beginner review checklist:\n[ ] I can write a clear goal\n[ ] I can add context and format\n[ ] I know how to verify a claim\n[ ] I know when to disclose AI use')}>Insert review checklist</button><CopyButton text={feedback} label="Copy feedback" /></div></div></div></section>
    </main><footer className="site-footer wrap"><span className="brand"><span className="brand-mark"><Sparkles size={14} /></span> AI Starter</span><span>Learn with curiosity. Check with care.</span><a href="#top">Back to top ↑</a></footer>
  </div>
}
